export const DEFAULT_WAIT_DELAY = 5000

export const POPULAR_MOVIE_CARD_TEST_ID = 'MOVIE_CARD_TEST_ID'
export const POPULAR_MOVIE_CARD_TITLE_TEST_ID = 'MOVIE_CARD_TITLE_TEST_ID'

export const MOVIE_SCREEN_HEADER_TEST_ID = 'MOVIE_SCREEN_HEADER_TEST_ID'

export const SEARCH_TAB_TEST_ID = 'SEARCH_TAB_TEST_ID'
export const SEARCH_INPUT_TEST_ID = 'SEARCH_INPUT_TEST_ID'
export const SEARCH_MOVIE_CARD_TEST_ID = 'SEARCH_MOVIE_CARD_TEST_ID'
export const SEARCH_MOVIE_CARD_TITLE_TEST_ID = 'SEARCH_MOVIE_CARD_TITLE_TEST_ID'
